### ISSUE TITLE
Variable not being declared

### ISSUE THREAD

**Issue by WaffleGamingUwU** [fiorescarlatto/four-tris#1]
On line 367 of the code in the main app, there is a variable not seen anywhere else in the code ($WH_KEYBOARD_LL) which causes the program to not run. I tried to delete it but of course it causes other errors elsewhere in the code. Not sure what to do. 
![image](https://user-images.githubusercontent.com/96221326/146310446-9f16284d-5239-43cb-8877-09c23e6f3735.png)

**Comment by WaffleGamingUwU** [comment]
I'm not sure if it's an issue with the application I'm using, my computer, or the program, because other people seem to run this just fine.

**Comment by torchlight** [comment]
I encountered the same problem; this can be fixed by adding `#include <WinAPIConstants.au3>` (where `WH_KEYBOARD_LL` is defined) to the top of Tetris.au3.
